suv =  {'/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Absil/SUV-ABSIL-PHILIPPE-20150625.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Berns/SUV-BERNS-STEFAN-20140807.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Boulakjar/SUV_BOULAKJAR-Anissa.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Bsilat/SUV-BSILAT-Ismail2011.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Collignon/SUV-COLLIGNON-JOHAN-20141204.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Coppens/SUV-COPPENS-Michel-mauvais.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Couto/SUV-COUTO-Domingos.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/DoHuynh/SUV-DO-HUYNH-20140626.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Kayapinar/SUV-KAYAPINAR_2012.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Laloux/SUV-LALOUX-NATHAN-20150122.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Lamoline/SUV-Lamoline.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Martins_Barrela_Miguel/SUV-MARTINS-BARRELA.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Moke/SUV-MOKE-Therese-6janvier11.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Verhasselt/SUV-VERHASSELT-STEPHANIE-20150416.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/sepulchre_2010/SUV_Sepulchre.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/Beekmans/SUV-BEEKMANS-ROBERTUS-20140515.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/Melchior/SUV-Melchior.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/PeetersTar/SUV-PEETERS.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/Rasquin/SUV-RASQUIN-AURELIE-20140424.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/Schwartz/SUV-SCHWARTZ-Kina.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/Marechal/SUV-MARECHAL-Anne_marie_2nd.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/Pellegrini/SUV-PELLEGRINI-21mars2013.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/PetinAN/SUV-PETIT_ANTOINE-NICOLAS_2010.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/Smprinis/SUV-SMPRINIS-Nikolaos.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/Van_Waterschoot_Willy/SUV-VavWaterschoot.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/WillemsAlbin/SUV-WILLEMS-ALBIN.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/siciliano_2012/SUV-SICILIANO_2012.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/yousoupov/SUV-YOUSOUPOV.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Baclin/SUV-Baclin.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Broekers/SUV-BROEKERS.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Casters/SUV-CASTERS-RICHARD_2011.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Decamp/SUV-DECAMP-FREDERIC.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Feug/SUV-acute-FUEG.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Filipov/SUV-FILIPOV-Valentin.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Forges/SUV-Forges.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/GaritteKaren/SUV-GARITTE-KAREN-20151126.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Haroutiounian/SUV-HAROUTIOUNIAN-Daniel.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Heinen/SUV-HEINEN-Pascal_2011.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Hullebusch/SUV-HULLEBUSCH-FRANS-20140313.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Jonen/SUV-JONEN-PASCAL-20140828.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Jourdan/SUV-JOURDAN-GATIEN-20141002.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/LUTUN_CLAIRE_11062012/SUV-LUTUN.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Lacomble/SUV-Lacomble-30-5-2013.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Laissoub/SUV-LAISSOUB-FAIZA.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Langlois/SUV-Langlois.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Lisoir/SUV-LISOIR-JEAN-20150115.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/MOUTSCHEN_BIJAN_07122009/SUV-MOUTSCHEN-Bijan-12mai2011.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Malle/SUV-MALLE-ANAIS-20150813.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Mourcia_Romuald/SUV-Mourcia-28-11-2013.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Munch/SUV-MUNCH-Jeremie.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Nelissen_stephane/SUV-NELISSEN-STEPHANE-20150326.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Nguyen/SUV-Nguyen.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/PAYEN_CORINNE/SUV-PAYEN-Corinne.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/ParmentierRoger/SUV-PARMENTIER.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Ponchin_Johan/SUV-PONCIN-Johan.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Rasch/SUV-RASCH.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Relecom_Sven/SUV-RELECOM-Sven.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Remacle/SUV-REMACLE-20130613.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Schmitt/SUV-SCHMITT-20110324.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Schoolmeesters/SUV-SCHOOLMEESTERS-ROBBY-20140220.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Simul/SUV-SIMUL-MICHEL-20141218.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Siraux/SUV-SIRAUX-GREGORY-20140403.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Smet/SUV-SMET-TOM-20150312.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Socquet_Carine/SUV-SOCQUET.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Tial/SUV-TIAL-BILAL-20151015.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/VanderborneStephanie/SUV-VAN_DEN_BORNE-STEPHANIE-20140821.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/VossenRoel/SUV-VOSSEN.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/ginoux/SUV-GINOUX-IRENE-20160211.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Ababou_2015/SUV-ABABOU-HAMID-20150205.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Bernaards/SUV-BERNAARDS-Siewerd.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Borne/SUV-BORNE-CLAIRE-20140619.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Carameaux/SUV_CARAMEAUX-Adelaide-10202011.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Fermont/SUV-FERMONT-LAURENCE-20160121.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/FrancoVincenzo/SUV-Franco_2012.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/LibertJ/SUV-Libert.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/MAES_FRANCK/SUV-MAES-Frank.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/PetryH/SUV-PETRY.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Roggeman_salome/SUV-ROGGEMAN-SALOME-20140814.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/SPIERKEL_PIMPRENELLE_10102011/SUV-SPIERKEL-PIMPRENELLE-2010.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/amalvy_axel/SUV-AMALVY-AXEL-20151001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/solvini_rocco/SUV-Solvini-acute.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Bodson/SUV-BODSON-JACQUES-20150604.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Demirova_gulistan/SUV-DEMIROVA-GULISTAN-20160114.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Driesen/SUV-DRIESEN-FABIAN-20151217.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Duclaire/SUV-DUCLAIRE-Fabian.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Ferreira/SUV-FERREIRA_DE_OLIVEIRA_SERGIO-20141120.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Fohn/SUV-FOHN-MURIEL-20131205.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Goffin/SUV-GOFFIN.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Goldbach/SUV-GOLDBACH-TIMOTHEUS-20151022.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Hansen/SUV-HANSEN-20130718.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Houdin/SUV-HOUDIN.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/MAGNETTO_ELIZABETTA/SUV-MAGNETTO-Elisabetha.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/MERTES/SUV-MERTES-RAINER-20150423.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/MUSSO_ANTONINA/SUV-MUSSO-Angelina.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Massy_Jonathan/SUV-Massy.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/MathieuG/SUV-MATHIEU-Guy.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Mol/SUV-MOL-20120802.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Richir_Christiane/SUV-RICHIR-20130425.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Roland/SUV-ROLAND-THIERRY-20150716.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Rolies_Jeanny/SUV-ROLIES-JEANNY-20140731.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Ronvaux/SUV-RONVAUX-MARC-20151203.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Rouwzeeuw/SUV-ROUZEEUW-20100312.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Thiabut_Patrice/SUV-THIBAUT-PATRICE-20140206.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/VERMEULEN_CEDRIC/SUV_Vermeulen.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Viscomi_Catarina/SUV-VISCOMI-CATERINA-20150409.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/mureddu/SUV-MUREDDU-MARIO-20160121.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/oudia_hacen/SUV-OUDIA-HACEN-20150924.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/stassin/SUV-STASSIN.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Bend1/SUV-P9.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Blan2/SUV-24.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/BoniFran/SUV-BONIVERT-FRANCOISE-20150210.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Caho3/SUV-20.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/CoulCami/SUV-COULEE-CAMILLE-20150304.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/DegrThib/SUV-DEGRAVE-THIBAUT-20150205.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Foidart13/SUV-29.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Geron14/SUV-11.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/HardVirg/SUV-HARDY-VIRGINIE-20150309.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/HensSabr/SUV-HENSENS-SABRINA-20150507.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/HerbNath/SUV-HERBILLON-NATHALIE-20150213.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/HoebValr/SUV-HOEBRECHTS-VALERIE-20150217.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/KataLonc/SUV-KATAM-LEANCE-20150325.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/KeutJacq/SUV-KEUTIENS-JACQUES-20150225.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Luyp5/SUV-26.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/PeraGoln/SUV-PERAT-SEGOLENE-20150415.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/SchoBroo/SUV-SCHOONBROODT-COLETTE-20150223.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/SimoDavi/SUV-SIMONIS-DAVID-20150127.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Squi6/SUV-13.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Tamblez11/SUV-25.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/TheuCath/SUV-THEUNISSEN-CATHERINE-20150220.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/ThysJess/SUV-THYS-JESSICA-20150218.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Tous7/SUV-31.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/ValfIsab/SUV-VALFRE-ISABELLE-20150504.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/VancWalt/SUV-VANKERCKHOVEN-WALTER-20150216.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/VeraPaul/SUV-VERACHTERT-PAULINE-20150407.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Wathelet16/SUV-22.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Zeev9/SUV-P2.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/Caliskan/SUV-CALISKAN-SEVGI-20150611.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/OLEMANS_WANNES/SUV-OLEMANS-Walles.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/PILS_ANNELIES/SUV-PILS-Anneliese.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/Peeters_Quentin2010/SUV-PEETERS-QUENTIN-20160225.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/Peiffer/SUV-PEIFFER-SEBASTIEN-20150604.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/Rinne_Paul/SUV-Rinne-Paul-acute.nii' };
                                                                 
t1_mri = {
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Absil/cors0647959P-0019-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Berns/cor20140811_131955t1mprtras007a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Boulakjar/corBOULAKJAR_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Bsilat/corBSILAT-Ismail_T1_2011.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Collignon/corCOLLIGNON-JOHAN_T1_20141204.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Coppens/corCOPPENS_MICHEL_20101206_01209686_004_t1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Couto/corCOUTO-Domingos_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/DoHuynh/cor20140630_133721t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Kayapinar/corKAYAPINAR_-_DOKER_T1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Laloux/corLALOUX_t1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Lamoline/corLAMOLINE_Luc_T1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Martins_Barrela_Miguel/cors3402426V-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Moke/corMoke_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/Verhasselt/cor20150420_135951t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/EMCS/sepulchre_2010/cors3205671E-0004-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/Beekmans/corBeekmans_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/Melchior/corMelchior_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/PeetersTar/corPEETERS_Tars_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/Rasquin/corRASQUIN_AURELIE_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/LIS/Schwartz/corSCHWARTZ_Kina_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/Marechal/corMARECHAL_Anne-Marie_t1_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/Pellegrini/corPELLEGRINI_21mars2013_T1_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/PetinAN/corPETIT_ANTOINE_NICOLAS_2010_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/Smprinis/corSMPRINIS_Nikolaos_T1_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/Van_Waterschoot_Willy/cor20101011_131823t1mprtras017a1001_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/WillemsAlbin/cor20110725_134835t1mprtras002a1001_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/siciliano_2012/cor20120625_135558t1mprtras002a1001_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS/yousoupov/cors0979194T-0002-00001-000001-01_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Baclin/corBACLIN_JEAN_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Broekers/corBROEKERS_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Casters/corCasters_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Decamp/corDECAMP_FREDERIC_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Feug/corFUEG_NATHALIE_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Filipov/cor20110124_133406t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Forges/corForges_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/GaritteKaren/cor20151130_142840t1mprtras007a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Haroutiounian/corHAROUTIOUNIAN_Daniel_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Heinen/cor20110530_140236t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Hullebusch/corHULLEBUSCH_FRANS_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Jonen/cor20140901_135414t1mprtras005a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Jourdan/coro20141006_132125t1mprtras006a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/LUTUN_CLAIRE_11062012/cors3426267D-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Lacomble/cor20130603_160734t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Laissoub/corLAISSOUB_FAIZA_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Langlois/coro20120416_143606t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Lisoir/corLISOIR_JEAN_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/MOUTSCHEN_BIJAN_07122009/cors0980462M-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Malle/cors3659386T-0030-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Mourcia_Romuald/cors3508236K-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Munch/corMUNCH_Jeremie_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Nelissen_stephane/cors0738029G-0012-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Nguyen/cors0035517M-0003-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/PAYEN_CORINNE/cors3372358X-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/ParmentierRoger/cor20120116_164531t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Ponchin_Johan/cors0614268E-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Rasch/corRASCH_BEATRICE_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Relecom_Sven/cors3361064C-0102-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Remacle/cors3124541T-0018-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Schmitt/corSCHMITT_THOMAS_T1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Schoolmeesters/corSCHOOLMEESTERS_ROBBY_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Simul/cor20141222_143558t1mprtras004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Siraux/corSIRAUX_GREGORY_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Smet/cor20150316_142402t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Socquet_Carine/cors3418035X-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/Tial/cors3655473W-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/VanderborneStephanie/cor20140825_132748t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/VossenRoel/cor20121217_132844t1mprtras004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCS+/ginoux/cors3688507V-0003-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Ababou_2015/cor20150209_133348t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Bernaards/corBERNAARDS_Siewerd_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Borne/cor20140623_141735t1mprtras004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Carameaux/corCarameaux_10202011_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Fermont/cors3701156F-0008-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/FrancoVincenzo/corFRANCO_Vincenzo_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/LibertJ/corLIBERT_Jerome_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/MAES_FRANCK/cors3191267H-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/PetryH/corPETRY_Henri_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/Roggeman_salome/cors3587085H-0006-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/SPIERKEL_PIMPRENELLE_10102011/cors3298580H-0003-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/amalvy_axel/cors3632323W-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/MCSm/solvini_rocco/cors0735558T-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Bodson/cors0485426C-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Demirova_gulistan/cors3658439E-0004-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Driesen/cors0511705H-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Duclaire/corDUCLAIRE_Fabian_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Ferreira/corFERREIRA_DE_OLIVEIRA_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Fohn/corFOHN_MURIEL_T1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Goffin/corGOFFIN_Claudy_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Goldbach/cors3675085S-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Hansen/corHANSEN_t1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Houdin/corHOUDIN_Nicole_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/MAGNETTO_ELIZABETTA/cors3329214S-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/MERTES/cors0501953T-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/MUSSO_ANTONINA/cors3325575E-0004-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Massy_Jonathan/cors0735558T-0014-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/MathieuG/corMATHIEU_GUY_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Mol/corMOL_Elsje_Maria_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Richir_Christiane/cors3494978H-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Roland/cors0413256H-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Rolies_Jeanny/cors3602525C-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Ronvaux/cors3672176F-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Rouwzeeuw/corROUZEEUW_FABIENNE_t1_mpr_tra.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Thiabut_Patrice/cors3561882A-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/VERMEULEN_CEDRIC/cor20100621_141435t1mprtras002a1001_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/Viscomi_Catarina/cor20150413_140814t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/mureddu/cors0328581V-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/oudia_hacen/cors3600738V-0005-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/UWS/stassin/cor20121008_133508t1mprtras002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Bend1/cororig_struct_Bend1.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Blan2/cororig_structBlan2.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/BoniFran/corBoniFran_20150110_102626s003a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Caho3/cororig_structCaho3.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/CoulCami/corCoulCami_20150321_104619s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/DegrThib/corDegrThib_20141227_093930s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Foidart13/cororig_structFoidart13.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Geron14/cororig_structGeron14.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/HardVirg/corHardVirg_20150207_083418s003a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/HensSabr/corHensSabri_20150409_143100s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/HerbNath/corHerbNath_20150110_123650s003a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/HoebValr/corHoebValr_20150321_125449s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/KataLonc/corKataLonc_20141227_113929s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/KeutJacq/corKeutJacq_20141227_083115s002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Luyp5/cororig_structLuyp5.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/PeraGoln/corPeraGoln_20150321_114955s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/SchoBroo/corSchoBroo_20150321_081502s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/SimoDavi/corSimoDavi_20150207_105543s003a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Squi6/cororig_structSqui6.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Tamblez11/cororig_structTamblez11.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/TheuCath/corTheuCath_20141227_124338s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/ThysJess/corThysJess_20150110_113450s002a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Tous7/cororig_structTous7.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/ValfIsab/corValsIsab_20150321_093029s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/VancWalt/corVancWalt_20141227_104005s004a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/VeraPaul/corVeraPaul_20150207_095143s003a1001.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Wathelet16/cororig_structWathelet16.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/controls/Zeev9/cororig_structZeev9.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/Caliskan/cors3555921C-0006-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/OLEMANS_WANNES/cors3335804K-0002-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/PILS_ANNELIES/cors3322662B-0025-00001-000001-01_struct.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/Peeters_Quentin2010/cors3256852M-0025-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/Peiffer/cors3616782C-0014-00001-000001-01.nii'
                                                                     '/home/coma_meth/Documents/ICA_PET/dartel/Alice_Yorgos_Jitka/subjects/exclude/Rinne_Paul/cors0634444Y-0002-00001-000001-01.nii'
                                                                     };
                                                                
for i = 1 : size(suv, 1)
    disp(suv(i))
    disp(t1_mri(i))
    matlabbatch{1}.cfg_basicio.file_dir.file_ops.cfg_named_file.name = 'T1';
    matlabbatch{1}.cfg_basicio.file_dir.file_ops.cfg_named_file.files = {t1_mri(i)};
    matlabbatch{2}.cfg_basicio.file_dir.file_ops.cfg_named_file.name = 'PET';
    matlabbatch{2}.cfg_basicio.file_dir.file_ops.cfg_named_file.files = {suv(i)};
    matlabbatch{3}.spm.spatial.preproc.channel.vols(1) = cfg_dep('Named File Selector: T1(1) - Files', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files', '{}',{1}));
    matlabbatch{3}.spm.spatial.preproc.channel.biasreg = 0.001;
    matlabbatch{3}.spm.spatial.preproc.channel.biasfwhm = 60;
    matlabbatch{3}.spm.spatial.preproc.channel.write = [0 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(1).tpm = {'/home/coma_meth/Documents/Progs/spm12/tpm/TPM.nii,1'};
    matlabbatch{3}.spm.spatial.preproc.tissue(1).ngaus = 1;
    matlabbatch{3}.spm.spatial.preproc.tissue(1).native = [1 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(1).warped = [1 1];
    matlabbatch{3}.spm.spatial.preproc.tissue(2).tpm = {'/home/coma_meth/Documents/Progs/spm12/tpm/TPM.nii,2'};
    matlabbatch{3}.spm.spatial.preproc.tissue(2).ngaus = 1;
    matlabbatch{3}.spm.spatial.preproc.tissue(2).native = [1 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(2).warped = [1 1];
    matlabbatch{3}.spm.spatial.preproc.tissue(3).tpm = {'/home/coma_meth/Documents/Progs/spm12/tpm/TPM.nii,3'};
    matlabbatch{3}.spm.spatial.preproc.tissue(3).ngaus = 2;
    matlabbatch{3}.spm.spatial.preproc.tissue(3).native = [1 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(3).warped = [0 1];
    matlabbatch{3}.spm.spatial.preproc.tissue(4).tpm = {'/home/coma_meth/Documents/Progs/spm12/tpm/TPM.nii,4'};
    matlabbatch{3}.spm.spatial.preproc.tissue(4).ngaus = 3;
    matlabbatch{3}.spm.spatial.preproc.tissue(4).native = [0 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(4).warped = [0 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(5).tpm = {'/home/coma_meth/Documents/Progs/spm12/tpm/TPM.nii,5'};
    matlabbatch{3}.spm.spatial.preproc.tissue(5).ngaus = 4;
    matlabbatch{3}.spm.spatial.preproc.tissue(5).native = [0 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(5).warped = [0 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(6).tpm = {'/home/coma_meth/Documents/Progs/spm12/tpm/TPM.nii,6'};
    matlabbatch{3}.spm.spatial.preproc.tissue(6).ngaus = 2;
    matlabbatch{3}.spm.spatial.preproc.tissue(6).native = [0 0];
    matlabbatch{3}.spm.spatial.preproc.tissue(6).warped = [0 0];
    matlabbatch{3}.spm.spatial.preproc.warp.mrf = 1;
    matlabbatch{3}.spm.spatial.preproc.warp.cleanup = 1;
    matlabbatch{3}.spm.spatial.preproc.warp.reg = [0 0.001 0.5 0.05 0.2];
    matlabbatch{3}.spm.spatial.preproc.warp.affreg = 'mni';
    matlabbatch{3}.spm.spatial.preproc.warp.fwhm = 0;
    matlabbatch{3}.spm.spatial.preproc.warp.samp = 3;
    matlabbatch{3}.spm.spatial.preproc.warp.write = [1 1];
    matlabbatch{4}.spm.spatial.normalise.write.subj(1).def(1) = cfg_dep('Segment: Forward Deformations', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','fordef', '()',{':'}));
    matlabbatch{4}.spm.spatial.normalise.write.subj(1).resample(1) = cfg_dep('Named File Selector: PET(1) - Files', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files', '{}',{1}));
    matlabbatch{4}.spm.spatial.normalise.write.subj(2).def(1) = cfg_dep('Segment: Forward Deformations', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','fordef', '()',{':'}));
    matlabbatch{4}.spm.spatial.normalise.write.subj(2).resample(1) = cfg_dep('Named File Selector: T1(1) - Files', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files', '{}',{1}));
    matlabbatch{4}.spm.spatial.normalise.write.woptions.bb = [-78 -112 -70
                                                              78 76 85];
    matlabbatch{4}.spm.spatial.normalise.write.woptions.vox = [2 2 2];
    matlabbatch{4}.spm.spatial.normalise.write.woptions.interp = 4;
    matlabbatch{5}.spm.spatial.smooth.data(1) = cfg_dep('Normalise: Write: Normalised Images (Subj 1)', substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('()',{1}, '.','files'));
    matlabbatch{5}.spm.spatial.smooth.data(2) = cfg_dep('Normalise: Write: Normalised Images (Subj 2)', substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('()',{2}, '.','files'));
    matlabbatch{5}.spm.spatial.smooth.fwhm = [4 4 4];
    matlabbatch{5}.spm.spatial.smooth.dtype = 0;
    matlabbatch{5}.spm.spatial.smooth.im = 0;
    matlabbatch{5}.spm.spatial.smooth.prefix = 's8';
    spm_jobman('serial', matlabbatch);

end